### ISSUE TITLE
Working with Lumen

### ISSUE THREAD

**Issue by olafura** [AbstractMachinesLab/lam#1]
There are a lot of commonalities between Lumen and LAM. I really like how fast LAM seems to be progressing and it's very interesting. What are you opinions about Lumen?

I think both can coexist, maybe sharing BIF implementations and other components.

https://github.com/lumen/lumen
https://github.com/lumen/eir

**Comment by leostera** [comment]
Hej @olafura! Thanks for opening the issue 🙌🏼 

I think that superficially Lumen and LAM seem to be on the same category, but we have rather different approaches.

Lumen seems to be translating Erlang sources to an intermediate representation (EIR) that gets lowered down to LLVM bytecode, and then hooks into the LLVM toolchain to produce crazy fast and really optimized binaries.

LAM begins at the BEAM bytecode level, which makes it a little easier to also use with Caramel / Elixir / Clojerl / Gleam, and it translates the bytecode to its own instruction set: .lam files (or LAM bytecode).

Then LAM has a runtime-agnostic emulator that can execute that translated bytecode, and uses a pluggable runtime to execute platform specific things (like FFIs, or threading, or DOM manipulation in the future).

These .lam files, the emulator, and one runtime, are bundled into a binary with a little boot code that stitches it all together. At the end of the day, there's still the overhead of having an emulator, which Lumen doesn't need.

I've got no doubt that there's a lot LAM can learn from Lumen, and I'll start looking to see if there are things we can share more eagerly. Off the top of my head there should be two:

1. as you mention, the BIF implementations, and 
2. BEAM-bytecode modules for reading / inspecting / writing it

---

One of the outcomes I'd like to have from LAM is also a _specification_ written in TLA+ that can be used to reason more cleanly about the behavior of it.  Perhaps this is also something that we can share 😄

**Comment by leostera** [comment]
I'll close this for the time being, thanks @olafura for bringing it up 🙌🏼
